# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zlib-crc32_combine}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["W. Andrew Loe III", "Aaron Patterson"]
  s.date = %q{2010-02-16}
  s.description = %q{Add Zlib's crc32_combine and adler32_combine to Ruby's Zlib}
  s.email = %q{andrew@andrewloe.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/zlib-crc32_combine.rb",
     "test/helper.rb",
     "test/test_zlib-crc32_combine.rb",
     "zlib-crc32_combine.gemspec"
  ]
  s.homepage = %q{http://github.com/loe/zlib-crc32_combine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Add Zlib's crc32_combine and adler32_combine to Ruby's Zlib}
  s.test_files = [
    "test/helper.rb",
     "test/test_zlib-crc32_combine.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 0.6.2"])
    else
      s.add_dependency(%q<ffi>, ["~> 0.6.2"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 0.6.2"])
  end
end

